# Generated by Django 3.0.6 on 2020-05-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_auto_20200508_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='english_example',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='dictionary',
            name='luganda_example',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='dictionary',
            name='word_form',
            field=models.CharField(choices=[('NOUN', 'Noun'), ('VERB', 'Verb'), ('PRONOUN', 'Pronoun'), ('ADJECTIVE', 'Adjective'), ('PREPOSITION', 'Preposition'), ('ADVERB', 'Adverb'), ('CONJUNCTION', 'Conjunction'), ('INTERJECTION', 'Interjection'), ('PHRASE', 'Phrase'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=12),
        ),
    ]
