# Generated by Django 3.0.6 on 2020-05-30 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0005_auto_20200530_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='last_edited',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
